name: validate-branch-flow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: read
  contents: read

jobs:
  branch-checks:
    uses: ZySec-AI/.github/.github/workflows/_reusable-branch-flow-check.yml@develop
    secrets: inherit
