name: PR checklist comment

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [develop]

permissions:
  pull-requests: write

jobs:
  comment:
    uses: ZySec-AI/.github/.github/workflows/_reusable-merge-comment.yml@develop
    secrets: inherit
